a = input('Digite algo:')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaço?', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfaqbetico? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Esta em maiúsculas? ', a.isupper())
print("Esta em minúsculas? ", a.islower())
print('Esta capitalizada? ', a.istitle())
