frase = str(input('Digite uma frase: ')).upper().strip()
print('Analise a frase....')
print('A letra A aparece {} vezes '.format(frase.count('A')))
print('A letra A aparece pela primera vez na posição {} '.format(frase.find('A')+1))
print('A letra A apareceu pela última vez na posição {} '.format(frase.rfind('A')+1))
